#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUTBOX                            100
#define IDI_MAINICON                            101
#define IDD_PROPPAGE_TRANSPARENT                102
#define IDD_VIEWING_WINDOWS                     103
#define IDD_DIALOG_UPDATEPROGRESS               105
#define IDD_PROPPAGE_HOTKEYS                    106
#define IDD_PROPPAGE_SYSTEM                     107
#define IDD_PROPPAGE_OSD                        108
#define IDR_MENU1                               109
#define IDC_STATIC_SENDMSG                      1000
#define IDC_CHECK_TRANSP_ALT                    1001
#define IDC_RADIO_SIZE_PROGRAM                  1001
#define IDC_CHECK_TRANSP_CTRL                   1002
#define IDC_CHECK_TRANSP_SHIFT                  1003
#define IDC_CHECK_TRANSP_WIN                    1004
#define IDC_CHECK_TOPMOST_ALT                   1005
#define IDC_CHECK_TOPMOST_CTRL                  1006
#define IDC_CHECK_TOPMOST_SHIFT                 1007
#define IDC_CHECK_TOPMOST_WIN                   1008
#define IDC_COMBO_TOPMOST_MSG                   1009
#define IDC_COMBO_MOVE_MSG                      1010
#define IDC_CHECK_AUTORUN                       1011
#define IDC_CHECK_MOVE_ALT                      1011
#define IDC_CHECK_MOVE_CTRL                     1012
#define IDC_CHECK_MOVE_SHIFT                    1013
#define IDC_SLIDER_MIN_TRANSP_LEVEL             1013
#define IDC_CHECK_MOVE_WIN                      1014
#define IDC_LIST_VIEWING_WINDOWS                1014
#define IDC_SLIDER_TRANSP_LEVEL_STEP            1014
#define IDC_COMBO_SIZE_MSG                      1015
#define IDC_RADIO_TOPLEFT                       1015
#define IDC_CHECK_SIZE_ALT                      1016
#define IDC_RADIO_TOPRIGHT                      1016
#define IDC_CHECK_SIZE_CTRL                     1017
#define IDC_RADIO_CENTER                        1017
#define IDC_CHECK_SIZE_SHIFT                    1018
#define IDC_RADIO_BOTLEFT                       1018
#define IDC_CHECK_SIZE_WIN                      1019
#define IDC_RADIO_BOTRIGHT                      1019
#define IDC_BUTTON_FONT                         1020
#define IDC_COMBO_TOGGLECAPTION_MSG             1020
#define IDC_BUTTON_TEXTCOLOR                    1021
#define IDC_CHECK_TOGGLECAPTION_ALT             1021
#define IDC_BUTTON_TEXTSHADOWCOLOR              1022
#define IDC_CHECK_TOGGLECAPTION_CTRL            1022
#define IDC_CHECK_TOGGLECAPTION_SHIFT           1023
#define IDC_STATIC_TEXTCOLOR                    1023
#define IDC_CHECK_TOGGLECAPTION_WIN             1024
#define IDC_STATIC_TEXTSHADOWCOLOR              1024
#define IDC_RADIO_NEVER                         1025
#define IDC_RADIO_ATSTART                       1026
#define IDC_RADIO_EVERY24HOURS                  1027
#define IDC_RADIO_ATSTARTANDEVERY24HOURS        1028
#define IDC_BUTTON_CHECKNOW                     1029
#define IDC_LIST_UPDATELOG                      1031
#define IDC_STATIC_DOWNLOADPAGE                 1032
#define IDM_ENABLE                              40000
#define IDS_MENU_ENABLE                         40000
#define IDM_DISABLE                             40001
#define IDS_MENU_DISABLE                        40001
#define IDM_RESTORE                             40002
#define IDS_MENU_RESTORE                        40002
#define IDM_VIEWING                             40003
#define IDS_MENU_QUIT                           40003
#define IDM_OPTIONS                             40004
#define IDS_APP_NAME                            40004
#define IDM_QUIT                                40005
#define IDS_MENU_OPTIONS                        40005
#define IDM_ABOUT                               40006
#define IDS_OPTIONSDLG_CAPTION                  40006
#define IDS_OPTOINS_COMBO_LBTN                  40007
#define IDS_OPTOINS_COMBO_RBTN                  40008
#define IDS_OPTOINS_COMBO_MBTN                  40009
#define IDS_COMPANY_NAME                        40010
#define IDS_MENU_ABOUT                          40011
#define IDS_MENU_VIEWING                        40012
#define IDS_VIEWING_LIST_COLUMN_CAPTION         40013
#define IDS_VIEWING_LIST_COLUMN_TRANSPARENT     40014
#define IDS_VIEWING_LIST_COLUMN_TRANSPARENT_LEVEL 40015
#define IDS_VIEWING_LIST_COLUMN_TOPMOST         40016
#define IDS_VIEWING_LIST_COLUMN_HIDECAPTION     40017
#define IDS_CHECKFORUPDATE_CONNECT              40018
#define IDS_CHECKFORUPDATE_CURRENTVERSION       40019
#define IDS_CHECKFORUPDATE_OK                   40020
#define IDS_CHECKFORUPDATE_FAIL                 40021
#define IDS_CHECKFORUPDATE_RECEIVEDATA          40022
#define IDS_CHECKFORUPDATE_PARSEDATA            40023
#define IDS_CHECKFORUPDATE_LASTVERSION          40024
#define IDS_CHECKFORUPDATE_NEWVERSIONAVAIL      40025
#define IDS_CHECKFORUPDATE_ERROR                40026
#define IDS_CHECKFORUPDATE_DATANAME             40027
#define IDS_DOWNLOADPAGE                        40028
#define IDS_DOWNLOAD_NOTIFY                     40029
#define IDS_DOWNLOAD_NOTIFY_CAPTION             40030
#define IDC_RADIO_MOVE_PROGRAM                  40031
#define IDS_SIZE_METHOD_BY_CORNER               40031
#define IDC_RADIO_MOVE_SYSTEM                   40032
#define IDS_SIZE_METHOD_BY_BORDER               40032
#define IDC_COMBO_SIZE_METHOD                   40036
#define IDC_RADIO_SIZE_SYSTEM                   40037
